package embedhash

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"errors"
	"fmt"
	"go/format"
	"hash"
	"io"
	"maps"
	"os"
	"path/filepath"
	"slices"

	"golang.org/x/tools/go/packages"
)

type config struct {
	varName        string
	hash           hash.Hash
	outputFilename string
}

type Result struct {
	Filename string
	PkgName  string
	VarName  string
	Data     map[string]string
}

func (r Result) Save(w io.Writer) error {

	if r.PkgName == "" {
		return errors.New("missing package name")
	}

	if r.VarName == "" {
		return errors.New("missing variable name")
	}

	buf := bytes.NewBuffer(nil)

	_, err := fmt.Fprintf(buf, "// Code generated by embedhash, DO NOT EDIT.\npackage %s\n\nvar %s = map[string]string{\n", r.PkgName, r.VarName)
	if err != nil {
		return err
	}

	keys := slices.Collect(maps.Keys(r.Data))

	slices.Sort(keys)

	for _, path := range keys {
		if _, err := fmt.Fprintf(buf, "\t%q: %q,\n", path, r.Data[path]); err != nil {
			return err
		}
	}

	if _, err := fmt.Fprint(buf, "}"); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	_, err = io.Copy(w, bytes.NewReader(formatted))

	return err
}

func getpackages(patterns ...string) ([]*packages.Package, error) {

	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedEmbedFiles,
		Dir:  ".",
	}

	return packages.Load(cfg, patterns...)

}

func hashEmbeddedFiles(pkg *packages.Package, hasher hash.Hash) (map[string]string, error) {

	if pkg == nil {
		return nil, errors.New("pkg is nil")
	}

	m := make(map[string]string)

	for _, file := range pkg.EmbedFiles {

		f, err := os.Open(file)
		if err != nil {
			return nil, errors.Join(fmt.Errorf("unable to read %s", file), err)
		}

		defer f.Close()

		info, err := f.Stat()
		if err != nil {
			return nil, errors.Join(fmt.Errorf("unable to get info for %s", file), err)
		}

		if info.IsDir() {
			continue
		}

		if _, err := io.Copy(hasher, f); err != nil {
			return nil, errors.Join(fmt.Errorf("unable to hash %s", file), err)
		}

		sum := hasher.Sum(nil)
		hasher.Reset()

		rel, err := filepath.Rel(pkg.Dir, file)
		if err != nil {
			rel = file
		}

		key := filepath.ToSlash(rel)
		m[key] = hex.EncodeToString(sum)

	}

	return m, nil
}

type Option interface {
	apply(*config) error
}

type option func(*config) error

func (o option) apply(c *config) error {
	return o(c)
}

func Hasher(h hash.Hash) Option {
	return option(func(c *config) error {
		if h == nil {
			return errors.New("hash is nil")
		}
		c.hash = h
		return nil
	})
}

func OutputVarName(varName string) Option {
	return option(func(c *config) error {

		if varName == "" {
			return errors.New("output variable is empty")
		}

		c.varName = varName

		return nil
	})
}

func OutputFileName(filename string) Option {
	return option(func(c *config) error {

		if filename == "" {
			return errors.New("filename is empty")
		}

		c.outputFilename = filepath.Base(filename)

		return nil
	})
}

func New(dir string, opts ...Option) ([]*Result, error) {

	cfg := config{
		varName:        "HashesForEmbedded",
		hash:           md5.New(),
		outputFilename: "embedhashes.go",
	}

	for _, opt := range opts {
		if opt == nil {
			continue
		}

		if err := opt.apply(&cfg); err != nil {
			return nil, err
		}
	}

	pkgs, err := getpackages(dir)
	if err != nil {
		return nil, err
	}

	var list []*Result

	for _, pkg := range pkgs {

		if pkg == nil {
			return nil, errors.New("package is nil")
		}

		outputName := pkg.Name

		embedVars := pkg.EmbedFiles

		if len(embedVars) == 0 {
			continue
		}

		result, err := hashEmbeddedFiles(pkg, cfg.hash)
		if err != nil {
			return nil, err
		}

		if len(result) == 0 {
			continue
		}

		list = append(list, &Result{
			Filename: filepath.Join(pkg.Dir, cfg.outputFilename),
			PkgName:  outputName,
			VarName:  cfg.varName,
			Data:     result,
		})

	}

	return list, nil

}
