package embedhash_test

import (
	"bytes"
	"crypto/sha256"
	"go/ast"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"testing"

	"github.com/hcarriz/embedhash"
)

func md5FixtureHashes() map[string]string {
	return map[string]string{
		"test.md":              "ceb0947a7db674632116cb7fefb5424e",
		"uhoh/02-number.txt":   "f55eb53829262e63db015ccfe5df61b9",
		"uhoh/10-number.txt":   "52c7b46426d576fd861e36251593c38b",
		"uhoh/Uppercase.txt":   "9be779e90541ab9fc3143db5ab4c6d5e",
		"uhoh/a-space.txt":     "ea949316d47f0f57a015569d2a0d6016",
		"uhoh/alpha.txt":       "e2e35117475aef27186668bff627f475",
		"uhoh/nested/deep.txt": "4f0a6b9d34e7590910f0f8ff0a8be139",
		"uhoh/uhoh.go":         "07e16a3b94e2bd127b42ce10d4d99c43",
		"uhoh/z-last.txt":      "c3fc492c2deafaca77a41d79b511b441",
	}
}

func sha256FixtureHashes() map[string]string {
	return map[string]string{
		"test.md":              "ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93",
		"uhoh/02-number.txt":   "795c955777c2fa1f68825807828a52978a41e6807eae43f808b116b836eff6b0",
		"uhoh/10-number.txt":   "8242377007f725417896e983428f3228c972098091d9657173b3f494d06dcf55",
		"uhoh/Uppercase.txt":   "e7488517ef7d36555a2f17b2850a59093d5ae5494d36709c5b9a9740a1634324",
		"uhoh/a-space.txt":     "b9815a98668299551bfeaae9c88e60fe9d05a0e46717349fd4baaed13db5f03a",
		"uhoh/alpha.txt":       "5a8f84e37289172b6d0ddbef5f7e46bba72491840b202a8c5b926dc38c08a652",
		"uhoh/nested/deep.txt": "2029543e317c6bdf62c7f85ba0123e27af56f0ae54cfc15048f6be6e69b32a95",
		"uhoh/uhoh.go":         "7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b",
		"uhoh/z-last.txt":      "17ca5e47de0b85e043a29abfdd13ee4729b99aa3fe400902d4b903c884b22f94",
	}
}

const wantGeneratedSHA256 = `// Code generated by embedhash, DO NOT EDIT.
package valid

var GenerateETags = map[string]string{
	"test.md":              "ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93",
	"uhoh/02-number.txt":   "795c955777c2fa1f68825807828a52978a41e6807eae43f808b116b836eff6b0",
	"uhoh/10-number.txt":   "8242377007f725417896e983428f3228c972098091d9657173b3f494d06dcf55",
	"uhoh/Uppercase.txt":   "e7488517ef7d36555a2f17b2850a59093d5ae5494d36709c5b9a9740a1634324",
	"uhoh/a-space.txt":     "b9815a98668299551bfeaae9c88e60fe9d05a0e46717349fd4baaed13db5f03a",
	"uhoh/alpha.txt":       "5a8f84e37289172b6d0ddbef5f7e46bba72491840b202a8c5b926dc38c08a652",
	"uhoh/nested/deep.txt": "2029543e317c6bdf62c7f85ba0123e27af56f0ae54cfc15048f6be6e69b32a95",
	"uhoh/uhoh.go":         "7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b",
	"uhoh/z-last.txt":      "17ca5e47de0b85e043a29abfdd13ee4729b99aa3fe400902d4b903c884b22f94",
}
`

func TestNew(t *testing.T) {

	dir, err := os.Getwd()
	if err != nil {
		t.Errorf("unable to get working directory: %v", err)
		return
	}

	type args struct {
		dir  string
		opts []embedhash.Option
	}
	tests := []struct {
		name    string
		args    args
		want    []*embedhash.Result
		wantErr bool
	}{
		{
			name: "default",
			args: args{
				dir: "./internal/valid",
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data:     md5FixtureHashes(),
				},
			},
			wantErr: false,
		},
		{
			name: "custom output filename",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.OutputFileName("something/out.go"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "out.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data:     md5FixtureHashes(),
				},
			},
			wantErr: false,
		},
		{
			name: "custom output name",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.OutputVarName("private"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "private",
					Data:     md5FixtureHashes(),
				},
			},
			wantErr: false,
		},
		{
			name: "all ops",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.Hasher(sha256.New()),
					embedhash.OutputFileName("test.go"),
					embedhash.OutputVarName("private"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "test.go"),
					PkgName:  "valid",
					VarName:  "private",
					Data:     sha256FixtureHashes(),
				},
			},
			wantErr: false,
		},
		{
			name: "sha256",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.Hasher(sha256.New()),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data:     sha256FixtureHashes(),
				},
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, err := embedhash.New(tt.args.dir, tt.args.opts...)
			if (err != nil) != tt.wantErr {
				t.Errorf("New() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("New() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestResult_Save(t *testing.T) {

	dir, err := os.Getwd()
	if err != nil {
		t.Errorf("unable to get working directory: %v", err)
		return
	}

	tests := []struct {
		name    string
		fields  embedhash.Result
		wantW   string
		wantErr bool
	}{
		{
			name: "default",
			fields: embedhash.Result{
				Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
				PkgName:  "valid",
				VarName:  "GenerateETags",
				Data:     sha256FixtureHashes(),
			},
			wantW:   wantGeneratedSHA256,
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			r := embedhash.Result{
				Filename: tt.fields.Filename,
				PkgName:  tt.fields.PkgName,
				VarName:  tt.fields.VarName,
				Data:     tt.fields.Data,
			}
			w := &bytes.Buffer{}
			if err := r.Save(w); (err != nil) != tt.wantErr {
				t.Errorf("Result.Save() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if gotW := w.String(); gotW != tt.wantW {
				t.Errorf("Result.Save() = %v, want %v", gotW, tt.wantW)
			}
		})
	}
}

func TestResultSaveSortsKeys(t *testing.T) {
	hashes := sha256FixtureHashes()
	result := embedhash.Result{
		PkgName: "valid",
		VarName: "GenerateETags",
		Data:    hashes,
	}

	generated := saveResult(t, result)
	file, err := parser.ParseFile(token.NewFileSet(), "embedhash.go", generated, 0)
	if err != nil {
		t.Fatalf("parsing generated source: %v", err)
	}

	var got []string
	ast.Inspect(file, func(node ast.Node) bool {
		entry, ok := node.(*ast.KeyValueExpr)
		if !ok {
			return true
		}
		key, ok := entry.Key.(*ast.BasicLit)
		if !ok {
			t.Fatalf("generated map key has type %T, want *ast.BasicLit", entry.Key)
		}
		path, err := strconv.Unquote(key.Value)
		if err != nil {
			t.Fatalf("unquoting generated map key %q: %v", key.Value, err)
		}
		got = append(got, path)
		return true
	})

	want := slices.Sorted(maps.Keys(hashes))
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("generated key order = %q, want %q", got, want)
	}
}

func TestResultSaveIsDeterministic(t *testing.T) {
	result := embedhash.Result{
		PkgName: "valid",
		VarName: "GenerateETags",
		Data:    sha256FixtureHashes(),
	}
	want := saveResult(t, result)

	for run := range 10 {
		got := saveResult(t, result)
		if !bytes.Equal(got, want) {
			t.Fatalf("Save() run %d produced unstable output:\n%s\nwant:\n%s", run, got, want)
		}
	}
}

func TestGenerationIsIdempotentWhenOutputIsEmbedded(t *testing.T) {
	tests := []struct {
		name           string
		outputFilename string
		opts           []embedhash.Option
	}{
		{
			name:           "default output filename",
			outputFilename: "embedhashes.go",
		},
		{
			name:           "custom output filename",
			outputFilename: "embedhash.go",
			opts: []embedhash.Option{
				embedhash.OutputFileName("embedhash.go"),
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeTestFile(t, filepath.Join(dir, "go.mod"), "module example.com/selfinclude\n\ngo 1.24\n")
			writeTestFile(t, filepath.Join(dir, "payload.txt"), "embedded payload\n")
			writeTestFile(t, filepath.Join(dir, "fixture.go"), `package fixture

import "embed"

//go:embed *
var files embed.FS
`)

			pattern := "file=" + filepath.Join(dir, "fixture.go")
			first := generateFixture(t, pattern, tt.outputFilename, tt.opts...)
			second := generateFixture(t, pattern, tt.outputFilename, tt.opts...)

			if !bytes.Equal(second, first) {
				t.Fatalf("second generation changed output:\n%s\nwant:\n%s", second, first)
			}
		})
	}
}

func TestGeneratedFixtureIsCurrent(t *testing.T) {
	results, err := embedhash.New(
		"./internal/valid",
		embedhash.OutputFileName("embedhash.go"),
	)
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("New() returned %d results, want 1", len(results))
	}

	var want bytes.Buffer
	if err := results[0].Save(&want); err != nil {
		t.Fatalf("Save() error = %v", err)
	}

	got, err := os.ReadFile(results[0].Filename)
	if err != nil {
		t.Fatalf("reading generated fixture: %v", err)
	}
	if !bytes.Equal(got, want.Bytes()) {
		t.Fatalf("generated fixture is stale:\n%s\nwant:\n%s", got, want.Bytes())
	}
}

func saveResult(t *testing.T, result embedhash.Result) []byte {
	t.Helper()

	var generated bytes.Buffer
	if err := result.Save(&generated); err != nil {
		t.Fatalf("Save() error = %v", err)
	}
	return generated.Bytes()
}

func generateFixture(t *testing.T, pattern, outputFilename string, opts ...embedhash.Option) []byte {
	t.Helper()

	results, err := embedhash.New(pattern, opts...)
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("New() returned %d results, want 1", len(results))
	}
	if got := filepath.Base(results[0].Filename); got != outputFilename {
		t.Fatalf("generated filename = %q, want %q", got, outputFilename)
	}
	if _, found := results[0].Data[outputFilename]; found {
		t.Fatal("generated output file was included in its own hash map")
	}

	generated := saveResult(t, *results[0])
	if err := os.WriteFile(results[0].Filename, generated, 0o600); err != nil {
		t.Fatalf("writing generated fixture: %v", err)
	}
	return generated
}

func writeTestFile(t *testing.T, filename, contents string) {
	t.Helper()
	if err := os.WriteFile(filename, []byte(contents), 0o600); err != nil {
		t.Fatalf("writing %s: %v", filename, err)
	}
}
