package embedhash_test

import (
	"bytes"
	"crypto/sha256"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/hcarriz/embedhash"
)

func TestNew(t *testing.T) {

	dir, err := os.Getwd()
	if err != nil {
		t.Errorf("unable to get working directory: %v", err)
		return
	}

	type args struct {
		dir  string
		opts []embedhash.Option
	}
	tests := []struct {
		name    string
		args    args
		want    []*embedhash.Result
		wantErr bool
	}{
		{
			name: "default",
			args: args{
				dir: "./internal/valid",
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data: map[string]string{
						"test.md":      "ceb0947a7db674632116cb7fefb5424e",
						"uhoh/uhoh.go": "07e16a3b94e2bd127b42ce10d4d99c43",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "custom output filename",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.OutputFileName("something/out.go"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "out.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data: map[string]string{
						"test.md":      "ceb0947a7db674632116cb7fefb5424e",
						"uhoh/uhoh.go": "07e16a3b94e2bd127b42ce10d4d99c43",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "custom output name",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.OutputVarName("private"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "private",
					Data: map[string]string{
						"test.md":      "ceb0947a7db674632116cb7fefb5424e",
						"uhoh/uhoh.go": "07e16a3b94e2bd127b42ce10d4d99c43",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "all ops",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.Hasher(sha256.New()),
					embedhash.OutputFileName("test.go"),
					embedhash.OutputVarName("private"),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "test.go"),
					PkgName:  "valid",
					VarName:  "private",
					Data: map[string]string{
						"test.md":      "ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93",
						"uhoh/uhoh.go": "7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b",
					},
				},
			},
			wantErr: false,
		},
		{
			name: "sha256",
			args: args{
				dir: "./internal/valid",
				opts: []embedhash.Option{
					embedhash.Hasher(sha256.New()),
				},
			},
			want: []*embedhash.Result{
				{
					Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
					PkgName:  "valid",
					VarName:  "HashesForEmbedded",
					Data: map[string]string{
						"test.md":      "ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93",
						"uhoh/uhoh.go": "7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b",
					},
				},
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got, err := embedhash.New(tt.args.dir, tt.args.opts...)
			if (err != nil) != tt.wantErr {
				t.Errorf("New() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("New() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestResult_Save(t *testing.T) {

	dir, err := os.Getwd()
	if err != nil {
		t.Errorf("unable to get working directory: %v", err)
		return
	}

	tests := []struct {
		name    string
		fields  embedhash.Result
		wantW   string
		wantErr bool
	}{
		{
			name: "default",
			fields: embedhash.Result{
				Filename: filepath.Join(dir, "internal", "valid", "embedhashes.go"),
				PkgName:  "valid",
				VarName:  "GenerateETags",
				Data: map[string]string{
					"test.md":      "ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93",
					"uhoh/uhoh.go": "7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b",
				},
			},
			wantW:   "// Code generated by embedhash, DO NOT EDIT.\npackage valid\n\nvar GenerateETags = map[string]string{\n\t\"test.md\":      \"ce2c0c0f63d540a03b17fe83aca6f9e3c344819a620418633332d5089e260c93\",\n\t\"uhoh/uhoh.go\": \"7b2c6436697f5def7aba84b91f5a87aabca63b36b1075947adbf2fa89dad143b\",\n}\n",
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			r := embedhash.Result{
				Filename: tt.fields.Filename,
				PkgName:  tt.fields.PkgName,
				VarName:  tt.fields.VarName,
				Data:     tt.fields.Data,
			}
			w := &bytes.Buffer{}
			if err := r.Save(w); (err != nil) != tt.wantErr {
				t.Errorf("Result.Save() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if gotW := w.String(); gotW != tt.wantW {
				t.Errorf("Result.Save() = %v, want %v", gotW, tt.wantW)
			}
		})
	}
}
