// Code generated by embedhash, DO NOT EDIT.
package valid

var HashesForEmbedded = map[string]string{
	"test.md":      "ceb0947a7db674632116cb7fefb5424e",
	"uhoh/uhoh.go": "07e16a3b94e2bd127b42ce10d4d99c43",
}
